### ISSUE TITLE
Proper schema introspection

### ISSUE THREAD

**Issue by micimize** [micimize/angel-starwars-test-server#1]
[GraphiQL complains about our schema's inconsistency](https://github.com/zino-app/graphql-flutter/issues/343), probably because we're working around angel graphql's lack of recursive type references:
```
Error: Character.friends expects type "[String]" but Droid.friends provides type "[Character]".
    at invariant (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:25010:11)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:29992:29
    at Array.forEach (<anonymous>)
    at assertObjectImplementsInterface (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:29983:30)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:29865:18
    at Array.forEach (<anonymous>)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:29864:30
    at Array.forEach (<anonymous>)
    at new GraphQLSchema (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:29861:32)
    at buildClientSchema (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:31250:10)
```

**Comment by micimize** [comment]
This should be fixed in `0.0.5`
